def import_all_models() -> None:
    import app.models.amazon_domain_throttle  # noqa: F401
    import app.models.audit_event  # noqa: F401
    import app.models.cbt_listing_config  # noqa: F401
    import app.models.collection_job  # noqa: F401
    import app.models.draft_listing_config  # noqa: F401
    import app.models.draft_pricing_config  # noqa: F401
    import app.models.integration_credential  # noqa: F401
    import app.models.keyword_collection_campaign  # noqa: F401
    import app.models.meli_metadata_cache  # noqa: F401
    import app.models.product_draft  # noqa: F401
    import app.models.product_draft_approval  # noqa: F401
    import app.models.provider_model_price  # noqa: F401
    import app.models.publish_job  # noqa: F401
    import app.models.review_result  # noqa: F401
    import app.models.review_job  # noqa: F401
    import app.models.source_product  # noqa: F401
    import app.models.store  # noqa: F401
    import app.models.token_credential  # noqa: F401
    import app.models.erp  # noqa: F401
